In [1]:
import pandas as pd

In [2]:
url = './data-maxtemp/timeseries-data/jma-maxtemp-heatpoints-by-pref-yearly.csv'

In [4]:
df = pd.read_csv(url)

In [14]:
df[df.pref=='大阪府']

,year,pref,over30,over30_capitol,over35,over35_capitol,over40,over40_capitol,over30_ytd,over30_capitol_ytd,over35_ytd,over35_capitol_ytd,over40_ytd,over40_capitol_ytd
26,2000,大阪府,89,85,31,26,0,0,51,47,16,11,0,0
73,2001,大阪府,78,77,29,21,0,0,49,49,22,15,0,0
120,2002,大阪府,89,86,28,22,0,0,54,53,16,14,0,0
167,2003,大阪府,72,66,11,7,0,0,35,31,2,1,0,0
214,2004,大阪府,103,94,26,20,0,0,60,52,21,16,0,0
261,2005,大阪府,102,88,23,8,0,0,58,51,14,7,0,0
308,2006,大阪府,78,71,27,17,0,0,48,42,10,8,0,0
355,2007,大阪府,83,79,21,16,0,0,36,32,2,1,0,0
402,2008,大阪府,84,71,24,13,0,0,48,41,19,11,0,0
449,2009,大阪府,86,73,9,3,0,0,50,39,6,1,0,0
496,2010,大阪府,94,82,40,31,0,0,50,42,13,9,0,0
543,2011,大阪府,82,76,27,7,0,0,44,44,15,5,0,0
590,2012,大阪府,87,75,27,12,0,0,43,36,17,10,0,0
637,2013,大阪府,99,88,35,23,0,0,57,50,21,10,0,0
684,2014,大阪府,85,65,9,5,0,0,54,39,8,5,0,0
731,2015,大阪府,73,58,18,11,0,0,50,38,17,11,0,0
778,2016,大阪府,92,81,28,26,0,0,54,44,12,11,0,0
825,2017,大阪府,83,74,20,15,0,0,50,43,16,12,0,0
872,2018,大阪府,81,74,36,27,0,0,49,45,26,20,0,0
919,2019,大阪府,95,80,25,19,0,0,51,41,15,10,0,0
966,2020,大阪府,81,70,25,22,0,0,44,35,3,1,0,0
1013,2021,大阪府,88,78,21,15,0,0,54,47,18,15,0,0
1060,2022,大阪府,103,87,31,14,0,0,57,47,19,11,0,0
1107,2023,大阪府,51,47,23,17,0,0,51,47,23,17,0,0

In [ ]:
df.groupby(['year'])[['over35','over35_capitol']].sum()

In [10]:
df.groupby(['year'])[['over35','over35_capitol']].sum()

      over35  over35_capitol
year
2000     678             391
2001     734             438
2002     661             379
2003     349             109
2004     789             369
2005     602             227
2006     690             299
2007     722             349
2008     785             351
2009     246              84
2010    1358             687
2011     739             298
2012     877             396
2013    1109             591
2014     439             215
2015     691             358
2016     849             409
2017     657             291
2018    1406             792
2019     817             419
2020    1017             578
2021     682             309
2022    1055             500
2023     922             517

In [8]:
df.groupby(['year'])[['over40','over40_capitol']].sum()

      over40  over40_capitol
year
2000       0               0
2001       2               1
2002       0               0
2003       0               0
2004       2               1
2005       0               0
2006       0               0
2007       5               0
2008       0               0
2009       0               0
2010       0               0
2011       0               0
2012       0               0
2013       7               2
2014       0               0
2015       0               0
2016       0               0
2017       0               0
2018      11               2
2019       4               0
2020       5               0
2021       1               0
2022       6               0
2023       1               0

In [6]:
df[df.over40==1]

,year,pref,over30,over30_capitol,over35,over35_capitol,over40,over40_capitol,over30_ytd,over30_capitol_ytd,over35_ytd,over35_capitol_ytd,over40_ytd,over40_capitol_ytd
56,2001,群馬県,57,52,16,15,1,1,41,39,16,15,1,1
63,2001,静岡県,81,54,18,5,1,0,50,32,18,5,1,0
200,2004,千葉県,86,68,18,3,1,0,52,43,15,2,1,0
203,2004,山梨県,95,86,18,17,1,1,61,56,14,14,1,1
339,2007,埼玉県,72,54,21,8,1,0,40,25,7,2,0,0
620,2013,群馬県,83,67,26,17,1,0,49,38,12,9,1,0
856,2018,埼玉県,84,70,40,23,1,0,55,43,30,18,1,0
857,2018,東京都,170,68,30,12,1,0,86,41,23,8,1,0
861,2018,山梨県,96,86,37,31,1,1,63,57,28,24,1,1
863,2018,愛知県,86,80,37,36,1,1,52,48,26,25,1,1
866,2018,新潟県,71,49,24,4,1,0,48,36,17,3,0,0
898,2019,山形県,56,43,14,11,1,0,33,27,9,7,0,0
915,2019,石川県,58,47,14,6,1,0,32,26,9,3,0,0
949,2020,群馬県,74,65,26,17,1,0,42,33,4,3,0,0
950,2020,埼玉県,68,56,28,17,1,0,36,24,6,4,0,0
960,2020,新潟県,64,43,15,6,1,0,26,14,3,1,0,0
1005,2021,岐阜県,87,71,25,15,1,0,51,43,20,10,1,0
1044,2022,埼玉県,76,67,29,19,1,0,44,41,25,18,1,0
1049,2022,山梨県,92,81,26,21,1,0,52,47,21,19,1,0
1052,2022,岐阜県,96,89,29,20,1,0,51,46,22,17,1,0
1087,2023,福島県,47,43,21,19,1,0,47,43,21,19,1,0