In [38]:
import requests
import pandas as pd
import numpy as np
from datetime import datetime

In [39]:
url = 'https://climatereanalyzer.org/clim/t2_daily/json/cfsr_world_t2_day.json'

In [40]:
response = requests.get(url)

In [41]:
data = response.json()

In [42]:
df_data = pd.DataFrame(data)

In [44]:
#flourishに読み込むデータ（df）はdate, year, tempで構成する

today = datetime.today().strftime('%Y-%m-%d')

dates = pd.date_range(start='1979-01-01', end=today)

# 月と日を取り出して文字列に変換し、連結する
month_day = dates.month.astype(str) + '/' + dates.day.astype(str)

# 年を取り出す
year = dates.year

# 新たなデータフレームを作成
df = pd.DataFrame({
    'date': month_day,
    'year': year
})

In [47]:
#df_dataの下3行は使わないので削除する必要あり

df_data = df_data.iloc[:-3]

In [49]:
temp = []

In [50]:
df_data.data[0]

[12.311,
 12.293,
 12.274,
 12.23,
 12.273,
 12.299,
 12.214,
 12.237,
 12.222,
 12.226,
 12.198,
 12.243,
 12.251,
 12.22,
 12.196,
 12.216,
 12.318,
 12.353,
 12.303,
 12.345,
 12.352,
 12.306,
 12.263,
 12.294,
 12.261,
 12.258,
 12.252,
 12.144,
 11.985,
 11.891,
 11.872,
 11.874,
 11.941,
 11.958,
 11.871,
 11.873,
 11.938,
 12.033,
 12.09,
 12.128,
 12.157,
 12.172,
 12.192,
 12.119,
 12.168,
 12.214,
 12.184,
 12.209,
 12.287,
 12.318,
 12.383,
 12.376,
 12.335,
 12.35,
 12.341,
 12.323,
 12.379,
 12.462,
 12.484,
 12.483,
 12.547,
 12.648,
 12.646,
 12.675,
 12.734,
 12.742,
 12.724,
 12.769,
 12.765,
 12.853,
 12.882,
 12.908,
 12.996,
 13.057,
 13.076,
 13.102,
 13.197,
 13.299,
 13.354,
 13.382,
 13.508,
 13.548,
 13.506,
 13.449,
 13.403,
 13.414,
 13.462,
 13.506,
 13.569,
 13.526,
 13.523,
 13.547,
 13.557,
 13.561,
 13.57,
 13.57,
 13.623,
 13.756,
 13.777,
 13.741,
 13.778,
 13.809,
 13.875,
 13.912,
 14.003,
 14.076,
 14.099,
 14.126,
 14.178,
 14.251,
 14.263,
 14.225,
 14.273,
 14.341,
 14.412,
 14.427,
 14.454,
 14.473,
 14.531,
 14.486,
 14.508,
 14.59,
 14.621,
 14.593,
 14.588,
 14.625,
 14.688,
 14.792,
 14.85,
 14.933,
 14.948,
 14.934,
 14.958,
 14.988,
 15.085,
 15.168,
 15.217,
 15.223,
 15.209,
 15.26,
 15.321,
 15.35,
 15.395,
 15.429,
 15.431,
 15.454,
 15.474,
 15.523,
 15.594,
 15.539,
 15.484,
 15.487,
 15.539,
 15.613,
 15.695,
 15.701,
 15.723,
 15.768,
 15.81,
 15.864,
 15.892,
 15.925,
 15.908,
 15.925,
 15.893,
 15.843,
 15.878,
 15.967,
 16.066,
 16.137,
 16.151,
 16.127,
 16.112,
 16.098,
 16.142,
 16.146,
 16.113,
 16.111,
 16.137,
 16.172,
 16.142,
 16.138,
 16.077,
 16.071,
 16.065,
 16.053,
 16.084,
 16.122,
 16.215,
 16.232,
 16.259,
 16.301,
 16.267,
 16.231,
 16.191,
 16.172,
 16.169,
 16.209,
 16.184,
 16.179,
 16.197,
 16.218,
 16.219,
 16.188,
 16.113,
 16.043,
 16.051,
 16.091,
 16.081,
 16.144,
 16.191,
 16.169,
 16.099,
 16.163,
 16.244,
 16.298,
 16.36,
 16.375,
 16.409,
 16.44,
 16.422,
 16.389,
 16.337,
 16.279,
 16.263,
 16.275,
 16.284,
 16.308,
 16.276,
 16.154,
 16.051,
 16.041,
 15.995,
 15.884,
 15.877,
 15.916,
 15.898,
 15.812,
 15.75,
 15.778,
 15.774,
 15.819,
 15.904,
 15.886,
 15.87,
 15.828,
 15.698,
 15.609,
 15.589,
 15.657,
 15.713,
 15.666,
 15.598,
 15.571,
 15.569,
 15.526,
 15.463,
 15.415,
 15.425,
 15.445,
 15.491,
 15.557,
 15.538,
 15.518,
 15.533,
 15.458,
 15.404,
 15.392,
 15.384,
 15.326,
 15.277,
 15.213,
 15.151,
 15.131,
 15.094,
 15.09,
 15.014,
 14.953,
 14.965,
 14.935,
 14.94,
 14.875,
 14.811,
 14.83,
 14.814,
 14.722,
 14.671,
 14.63,
 14.566,
 14.493,
 14.372,
 14.295,
 14.302,
 14.238,
 14.177,
 14.127,
 14.097,
 14.059,
 14.019,
 13.922,
 13.817,
 13.795,
 13.746,
 13.74,
 13.72,
 13.642,
 13.542,
 13.452,
 13.375,
 13.328,
 13.331,
 13.286,
 13.223,
 13.136,
 13.048,
 13.039,
 13.105,
 13.161,
 13.232,
 13.304,
 13.339,
 13.338,
 13.294,
 13.282,
 13.293,
 13.296,
 13.286,
 13.337,
 13.345,
 13.286,
 13.282,
 13.259,
 13.175,
 13.076,
 13.011,
 12.977,
 13.009,
 13.081,
 13.141,
 13.154,
 13.131,
 13.078,
 13.027,
 12.998,
 12.955,
 12.906,
 12.821,
 12.789,
 12.762,
 12.774,
 12.767,
 12.734,
 12.759,
 12.746,
 12.754,
 12.706,
 12.663,
 12.659,
 12.697,
 12.743,
 12.694,
 12.636,
 12.585,
 12.512,
 12.405,
 None]

In [52]:
#閏年でない年は、最後にnoneが入っているから取り除く必要あり

for i in range(len(df_data)):
    list_with_none = df_data.data[i]
    list_without_none = [x for x in list_with_none if x is not None]
    
#noneを取り除いたリストができたので、tempリストに集約（）
    
    for k in range(len(list_without_none)):
        temp.append(round(list_without_none[k], 2))

In [53]:
#本日の日付までデータが更新されているわけではないため、tempの数とdfの行数は異なる
#なので足りない分、temp列をNaNで埋める

df['temp'] = pd.Series(np.nan, index = df.index)

In [54]:
#あるだけtempデータを入れる

df.loc[df.index[:len(temp)], 'temp'] = temp

In [55]:
df = df.dropna()

In [56]:
df_without_229 = df[~df['date'].str.contains('^2/29$', regex=True)]

In [57]:
df_without_229 = df_without_229[['temp', 'year', 'date']]

In [59]:
df_without_229.to_csv("world_temperature.csv")