In [9]:
!pip install datetime

Collecting datetime
  Downloading DateTime-5.2-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.2/52.2 kB 1.4 MB/s eta 0:00:00
Collecting zope.interface (from datetime)
  Downloading zope.interface-6.0-cp311-cp311-macosx_10_9_x86_64.whl (202 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.3/202.3 kB 3.7 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: pytz in /Users/mio/.pyenv/versions/3.11.3/lib/python3.11/site-packages (from datetime) (2023.3)
Requirement already satisfied: setuptools in /Users/mio/.pyenv/versions/3.11.3/lib/python3.11/site-packages (from zope.interface->datetime) (65.5.0)
Installing collected packages: zope.interface, datetime
Successfully installed datetime-5.2 zope.interface-6.0

[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: pip install --upgrade pip

In [10]:
#amedasから最新の気象データを取得する

#import dependencies
import requests
import pandas as pd
from datetime import datetime,timedelta

#data1: 地点情報
url = 'https://www.jma.go.jp/bosai/amedas/const/amedastable.json'
r = requests.get(url)
data1 = r.json()

#data2: amedasの最新気象データ
##最新の時刻
r = requests.get('https://www.jma.go.jp/bosai/amedas/data/latest_time.txt')
latest_time = r.text
latest_time = datetime.strptime(latest_time, '%Y-%m-%dT%H:%M:%S%z').strftime('%Y%m%d%H0000')
print(latest_time)

##最新のデータ
url = f"https://www.jma.go.jp/bosai/amedas/data/map/{latest_time}.json"
r = requests.get(url)
data2 = r.json()

#data1とdata2を統合
amedas_data = {key: {**data1.get(key, {}), **data2.get(key, {})} for key in set(data1) | set(data2)}

#データ整形
amedas = pd.DataFrame(amedas_data)
amedas = amedas.T.rename_axis('amdno').reset_index()

##geo-cordをととのえる
amedas[['lat','lon']] = amedas[['lat','lon']].applymap(lambda x: x[0] + x[1]/60)

##残りのリスト形式のデータから値のみ抽出
amedas = amedas.applymap(lambda x: x[0] if type(x)==list else x)

#amedas.to_csv('./data/amedas_latest_data.csv',encoding='utf-8-sig',index=False)

20230728170000

In [13]:
amedas.shape

(1287, 28)

In [17]:
amedas.dropna(subset=['temp'])

,amdno,type,elems,lat,lon,alt,kjName,knName,enName,temp,...,precipitation1h,precipitation3h,precipitation24h,windDirection,wind,snow,pressure,normalPressure,visibility,weather
0,68156,C,11112010,35.331667,132.730000,20,出雲,イズモ,Izumo,33.6,...,0.0,0.0,0.0,3.0,4.2,NaN,NaN,NaN,NaN,NaN
1,21126,C,11112100,42.761667,142.143333,56,穂別,ホベツ,Hobetsu,28.7,...,0.0,0.0,0.0,9.0,2.8,NaN,NaN,NaN,NaN,NaN
2,20356,C,11112100,43.076667,142.840000,178,新得,シントク,Shintoku,31.6,...,0.0,0.0,0.0,13.0,3.0,NaN,NaN,NaN,NaN,NaN
3,82101,C,11112010,33.713333,130.975000,9,行橋,ユクハシ,Yukuhashi,31.1,...,0.0,0.0,0.0,2.0,2.6,NaN,NaN,NaN,NaN,NaN
5,74056,C,11112010,33.765000,133.338333,605,本川,ホンガワ,Hongawa,24.2,...,0.0,0.0,0.0,15.0,0.7,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1278,34012,C,11112100,38.913333,140.828333,525,駒ノ湯,コマノユ,Komanoyu,28.0,...,0.0,0.0,0.0,11.0,0.9,NaN,NaN,NaN,NaN,NaN
1280,48767,B,11111111,35.523333,137.821667,516,飯田,イイダ,Iida,26.2,...,0.0,1.5,2.5,14.0,2.8,NaN,955.4,1013.9,20000.0,1.0
1281,83341,C,11112010,33.065000,131.631667,121,犬飼,イヌカイ,Inukai,33.2,...,0.0,0.0,0.0,4.0,1.2,NaN,NaN,NaN,NaN,NaN
1282,15076,C,11112100,44.010000,142.160000,159,幌加内,ホロカナイ,Horokanai,28.3,...,0.0,0.0,0.0,13.0,1.9,NaN,NaN,NaN,NaN,NaN
1284,15041,C,11112100,44.281667,142.161667,255,朱鞠内,シュマリナイ,Shumarinai,25.5,...,0.0,0.0,0.5,9.0,0.5,NaN,NaN,NaN,NaN,NaN